### ISSUE TITLE
Allow preservation of data in online Data Sources when a creator copies their own app

### ISSUE THREAD

**Issue by MrTwoCanes** [thunkable/thunkable-issues#654]
Thunkable X

For the second time in 8 days, the Data Source Tables crash when Creating or Updating; reads (gets) work.  This problem affects both Tables and AirTables.  First happened late Thursday, 8/27 (PDT) and was working again on  8/31 PDT.

Now, as of 9/2,  it is broken in the same way. I reported this yesterday and it wasn't addressed as of this morning.

![Screenshot from 2020-09-03 09-54-00](https://user-images.githubusercontent.com/67872003/92144410-8690c500-edcb-11ea-9c8c-f09ea67d84d4.png)

Any attempt to update value in Test Table either crashes the app, or the app simply won't continue past the attempted update.

Please fix this asap, I am dead in the water until it has been resolved.

**Comment by josmas** [comment]
Is this still an issue?

**Comment by Rojroj101** [comment]
yeah I think so. I've been going crazy too.. can't update my app that
people are using tonight :(

**Comment by MrTwoCanes** [comment]
Yes.  App still crashes.  Still a lack of alacrity in getting it fixed.  My app was ready to go.  I made a few cosmetic changes and BOOM, it stopped working.  Went back to older versions and they were broken as well.  Now my app has been waiting to go up on Play Store for 3 weeks.  I spent 8 weeks coding it and it broke in 8 seconds.

**Comment by StevenPurn** [comment]
@MrTwoCanes @Rojroj101 Sorry for the delay on this one. We had a solution that we thought would work but in testing it wasn't quite good enough so we had to take some extra time to get a fix together. If you update your Thunkable Live apps now (to version 222) it should be fixed. Please give those a try and let us know if you're still running into any issues.

**Comment by MrTwoCanes** [comment]
Great.  It doesn't crash any more, but there are still problems.  The ListViews seem to work, but the Data Source Tables are still broken.

When copying a project, instead of getting copies of my AirTables, it creates Thunkable Data Source tables that lose all my AirTables data.

![Screenshot from 2020-09-24 13-19-11](https://user-images.githubusercontent.com/67872003/94196319-08bf5700-fe69-11ea-94a7-06fdfa8204f9.png)

Multiple tables are affected, so it making a copy or checkpoint is useless.  I can't copy my project to a Play Store version, so I'm still dead in the water.

Thanks for your efforts.

**Comment by StevenPurn** [comment]
Thanks for confirming. This behavior when copying is intentional though we do have plans to improve the experience of copying a project. Basically the issue is that you can copy other users' projects and we don't have any way to indicate whether you would want your data to be allowed to be copied by other users. So, for now, we replace it all by default in copies. We have a few ideas as to what we can do to make this easier and more functional for our users but we don't have anything concrete that we're ready to talk about yet. Look for more information on this soon.

**Comment by MrTwoCanes** [comment]
Hmm.  You broke it on purpose?  How am I supposed to use AirTables now?  My project is private, I don't want any copies made by other users to start with.  Do you have any idea how difficult it is to replace all the CRUDs with new table names?  And who knows what will happen if I create all new Data Source tables and then copy the project.  My project was ready to go three weeks ago.  All I needed to do was make some cosmetic changes and change the app name to post it out on Play Store.  Now I'm dead in the water again.  I think this decision needs revisiting, especially for Private projects.

**Comment by StevenPurn** [comment]
Thanks for the feedback, we will take that into consideration. Sorry that it has made your experience worse; that certainly isn't what we intended. Like I said, we have some plans to make this process easier and it should address your concerns. Hopefully we can get things finalized and released soon.

**Comment by MrTwoCanes** [comment]
I note that copying Data Source Tables _**seems**_ to be working after the last update.  How about AirTables?  They are still not copying correctly when copying a project.  The "copied" tables have "Thunkable" in all the cells.

**Comment by StevenPurn** [comment]
Yes, the work on Airtable and Google Sheets isn't complete yet. It is still in process.

**Comment by vaskarni** [comment]
I am making a copy in my own workspace for my use. I am not worried about my API key/ Base ID of Airtable being compromised because it is a 'private' project. After I had a project working I wanted to make a copy to try out a new feature and not risk messing up a working version. 

Would you please consider allowing a copy but maybe wipe out the API key/ Base ID?

**Comment by jane-d-alt** [comment]
Since the original issue was resolved, but there is discussion of another feature request in the comments, the title of this issue has been updated to reflect the outstanding feature request.

**Comment by jane-d-alt** [comment]
Hi there,

As of the [May 27 2021](https://docs.thunkable.com/release-notes#may-27-2021) update, Data Sources are now preserved when a project is copied within the same account. 

If you remix your project, the Data Sources will remain connected. If somebody else remixes your project, the Data Sources will still be disconnected as seen when this request was originally made.

We will close this issue now. Thanks for the request! We hope this update makes building with Thunkable easier and more enjoyable for you.
